name: TapBiz
description: A new Flutter project.
publish_to: none
version: 1.0.30+50
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_local_notifications: ^16.3.2
  dio: ^5.4.0
  universal_io: ^2.2.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  flutter_html: ^3.0.0-alpha.6
  shimmer: ^3.0.0
  shared_preferences: ^2.1.1
  package_info_plus: ^3.0.3
  url_launcher: ^6.1.9
  pin_code_fields: ^8.0.1
  timeline_tile: 2.0.0
  google_fonts: ^4.0.4
  date_format: 2.0.7
  fab_circular_menu: 1.0.2
  # flutter_typeahead: ^5.0.2
  flutter_typeahead: 4.1.1
  backdrop: ^0.9.1
  # badges: ^3.1.2
  badges: 2.0.3
  flutter_barcode_scanner: 2.0.0
  battery_plus: ^5.0.2
  convex_bottom_bar: ^3.2.0
  device_info_plus: ^8.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_windowmanager: 0.2.0
  waterfall_flow: ^3.0.3
  percent_indicator: ^4.2.3
  like_button: 2.0.5
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  photofilters: 3.0.1
  image_cropper: ^4.0.1
  flutter_screenutil: ^5.9.0
  share_plus: ^6.3.4
  flutter_signature_pad: 3.0.1
  signature: ^5.3.0
  audioplayers: ^5.2.1
  sticky_headers: 0.3.0+2
  video_player: ^2.8.2
  flick_video_player: ^0.7.0
  visibility_detector: ^0.4.0+2
  # webview_flutter: ^4.4.4
  webview_flutter: 3.0.4
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  flutter_native_timezone: 2.0.0
  sliding_up_panel: 2.0.0+1
  geocoding: ^2.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  fluttericon: ^2.0.0
  intl: ^0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  path_provider: ^2.0.15
  http_interceptor: ^1.0.2
  flutter_radio_slider: ^0.1.0
  line_awesome_flutter: ^2.0.0
  formz: ^0.6.0
  get: ^4.6.5
  syncfusion_flutter_charts: ^24.1.47+1
  syncfusion_flutter_core: ^24.1.47
  qr_flutter: ^4.1.0
  restart_app: ^1.2.1
  flutter_slidable: ^3.0.1
  dotted_border: ^2.1.0
  firebase_messaging: ^14.7.10
  geolocator: ^10.1.0
  maps_launcher: ^2.2.0
  flutter_image_compress: ^2.0.3
  rflutter_alert: ^2.0.7
  flutter_calendar_carousel: ^2.4.2
  ndef: ^0.3.3
  flutter_nfc_kit: ^3.4.2
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.2
  crop_image: ^1.0.11
  otp_text_field: ^1.1.3
  flutter_custom_clippers: ^2.1.0
  stylish_bottom_bar: ^1.0.3
  salomon_bottom_bar: ^3.3.2
  qr_code_scanner: ^1.0.1
  email_validator: ^2.1.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/devkit/google_fonts/Audiowide-Regular.ttf
    - family: Bariol
      fonts:
        - asset: assets/devkit/fonts/Bariol_Regular.otf
        - asset: assets/devkit/fonts/Bariol_Thin.otf
          weight: 100
        - asset: assets/devkit/fonts/Bariol_Thin_Italic.otf
          weight: 100
          style: italic
        - asset: assets/devkit/fonts/Bariol_Light.otf
          weight: 300
        - asset: assets/devkit/fonts/Bariol_Light_Italic.otf
          weight: 300
          style: italic
        - asset: assets/devkit/fonts/Bariol_Bold.otf
          weight: 700
  assets:
  
    - assets/subimages/LOGOtapbiz putih_#f78d1e-01.png
    - assets/subimages/dta.png
    - assets/subimages/icon_man.png
    - assets/subimages/SPR.png
    - assets/subimages/logo_dark.png
    - assets/subimages/logo_dark2.png
    - assets/subimages/logo_dark3.png
    - assets/subimages/logo_horizontal.png
    - assets/subimages/logo_horizontal2.png
    - assets/subimages/logo_horizontal3.png
    - assets/subimages/logo_horizontal4.png
    - assets/subimages/logo_horizontal5.png
    - assets/subimages/logo_horizontal_tapbiz.png
    - assets/subimages/logo_horizontal_tapbizTr.png
    - assets/subimages/MasterLogo150.png
    - assets/subimages/MasterLogo1024x1024Tr.png
    - assets/subimages/MasterLogo500x210Tr.png
    - assets/subimages/ws_hb_digital.png
    - assets/devkit/images/logo_light.png
    - assets/devkit/images/logo_dark.png
    - assets/devkit/images/logo_horizontal.png
    - assets/devkit/images/lamp.jpg
    - assets/devkit/images/google.png
    - assets/devkit/images/facebook.png
    - assets/devkit/images/twitter.png
    - assets/devkit/images/whatsapp.png
    - assets/devkit/images/placeholder.jpg
    - assets/devkit/images/visa.png
    - assets/devkit/images/mastercard.png
    - assets/devkit/images/direction.png
    - assets/devkit/images/stop.png
    - assets/devkit/images/lang/en.png
    - assets/devkit/lang/en.json
    - assets/devkit/html/webview.html
flutter_icons:
  # android: false
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: assets/subimages/MasterLogo1024x1024Trv2.png
  image_path_ios: assets/subimages/MasterLogo1024x1024v2.png
  adaptive_icon_background: '#ffffff'